// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BarEchart: typeof import('./src/components/page-echarts/src/bar-echart.vue')['default']
    LineEchart: typeof import('./src/components/page-echarts/src/line-echart.vue')['default']
    MapEchart: typeof import('./src/components/page-echarts/src/map-echart.vue')['default']
    NavHeader: typeof import('./src/components/nav-header/src/nav-header.vue')['default']
    NavMenu: typeof import('./src/components/nav-menu/src/nav-menu.vue')['default']
    PageContent: typeof import('./src/components/page-content/src/page-content.vue')['default']
    PageModal: typeof import('./src/components/page-modal/src/page-modal.vue')['default']
    PageSearch: typeof import('./src/components/page-search/src/page-search.vue')['default']
    PieEchart: typeof import('./src/components/page-echarts/src/pie-echart.vue')['default']
    RoseEchart: typeof import('./src/components/page-echarts/src/rose-echart.vue')['default']
    UserInfo: typeof import('./src/components/nav-header/src/cpns/user-info.vue')['default']
  }
}

export { }
